# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0F1419'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black = '#01060E'
red = '#EA6C73'
green = '#91B362'
yellow = '#F9AF4F'
blue = '#53BDFA'
magenta = '#FAE994'
cyan = '#90E1C6'
white = '#C7C7C7'

# Bright colors
[colors.bright]
black = '#686868'
red = '#F07178'
green = '#C2D94C'
yellow = '#FFB454'
blue = '#59C2FF'
magenta = '#FFEE99'
cyan = '#95E6CB'
white = '#FFFFFF'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Roboto Mono Nerd Font"

#[shell]
#program = "/home/ushinnary/.cargo/bin/nu"
#args = ['-e', 'zellij']

[window]
opacity = 1
#opacity = 0.3
#blur = true
#decorations = "Transparent"

#[colors]
#transparent_background_colors = true
