[colors.primary]
background = "#08080b"
foreground = "#787c99"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Adwaita Mono"

#[shell]
#program = "/home/ushinnary/.cargo/bin/nu"
#args = ['-e', 'zellij']

[window]
opacity = 1
#opacity = 0.3
#blur = true
#decorations = "Transparent"

#[colors]
#transparent_background_colors = true
