[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.cursor]
cursor = "0xa277ff"

[colors.bright]
black = "0x4d4d4d"
blue = "0xa277ff"
cyan = "0x61ffca"
green = "0x61ffca"
magenta = "0xa277ff"
red = "0xff6767"
white = "0xededed"
yellow = "0xffca85"

[colors.normal]
black = "0x110f18"
blue = "0xa277ff"
cyan = "0x61ffca"
green = "0x61ffca"
magenta = "0xa277ff"
red = "0xff6767"
white = "0xedecee"
yellow = "0xffca85"

[colors.primary]
background = "0x15141b"
foreground = "0xedecee"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Cousine Nerd Font Mono"


[window]
opacity = 1
