"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌───────────────────>](bold green) $rust$nodejs$lua$package
[│](bold green)$directory$git_branch$git_status$username
[└─>](bold green) '''
add_newline = true

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
#vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'
format = "Ram: $symbol[$ram]($style) "

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"
