# IMPORTANT: This is a template file!
# Replace this with the actual hardware-configuration.nix generated by:
# sudo nixos-generate-config --show-hardware-config
#
# The Zotac Zone uses AMD Ryzen 7 8840U with Radeon 780M iGPU
# Run the command above on the actual device and replace this content

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Zotac Zone uses AMD Ryzen 7 8840U (Hawk Point)
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "thunderbolt" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # PLACEHOLDER: Update with actual UUIDs from your device
  # Use `lsblk -f` to find your partition UUIDs
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/PLACEHOLDER-ROOT-UUID";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/PLACEHOLDER-BOOT-UUID";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
