{
  imports = [
    ./lang/nix.nix
    ./lang/lua.nix
    ./lang/md.nix
    ./lang/nushell.nix
    ./lualine.nix
    ./autosave.nix
    ./yazi.nix
    ./toggleterm.nix
    ./smear-cursor.nix
    ./bufferline.nix
    ./notify.nix
    ./ts-comments.nix
    ./lsp/blink.nix
    ./lsp/lsp.nix
    ./lsp/ast_grep.nix
    ./gitsigns.nix
    ./web-devicons.nix
    ./nix-develop.nix
  ];
}
